### ISSUE TITLE
TAZ 6 Aerostruder E-steps should default to 420, not 830

### ISSUE THREAD

**Issue by b-morgan** [drunken-octopus/drunken-octopus-marlin#20]
### Description

In rc18, the firmware for the Angelfish_Aerostruder defaults to E-steps (M92) of 830. In the last version of LulzBot firmware (1.1.9.34), the Aerostruder has an E-steps of 420. Unlike the Single Extruders (and the Dual Extruders V2, and V3) which are delivered with a E-steps sticker, the Aerostruder tolerances are tight enough that 420 is a good starting point for all of them.

### Steps to Reproduce

1. Load Aerostruder firmware.
2. Heat the nozzle.
3. Load filament and mark at 20mm increments.
4. Extrude 10mm of filament.

**Expected behavior:** [What you expect to happen]

10mm of filament should be extruded (i.e. half way to the first mark).

**Actual behavior:** [What actually happens]

Almost 20mm of filament is extruded.

#### Additional Information

It might be worth comparing the LulzBot 1.1.9.34 .config files in [http://devel.lulzbot.com/software/Marlin/1.1.9.34/](http://devel.lulzbot.com/software/Marlin/1.1.9.34/) and setting better default E-steps for the other Aerostruder (or all?) toolheads. I think all the E3D based toolheads might need inspecting.

**Comment by marciot** [comment]
@b-morgan: The default is 420. When you flash new firmware, you need to "Reset to Factory Settings", otherwise it will take whatever E-steps were stored in the EEPROM, which will correspond to what ever toolhead you had before.
