### ISSUE TITLE
Machine Name specified in sample Taz Workhorse configuration is "Taz Workhorse". Cura LE 3.6.21 requires this to be "Taz Workhorse Edition" to be able to connect (without changing preferences to allow connection to "wrong printers")

### ISSUE THREAD

**Issue by SwiftNinja** [drunken-octopus/drunken-octopus-marlin#23]
Pretty self explanatory; easy fix.

I might suggest implementing the Custom LCD  Welcome Message in DrunkenOctopus, because "Taz Workhorse Edition Ready..." takes more space than is available and requires a scroller. I suspect this is why you shortened it, but it breaks out-of-the-box compatibility with the admittedly ancient Cura LE currently available.

**Comment by marciot** [comment]
This is an easy fix. I'll make the change.

**Comment by SwiftNinja** [comment]
Cheers.
